### ISSUE TITLE
Build problems 

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/etl_manager#108]
If you try and install etl manager using either 

```
pip install git+git://github.com/moj-analytical-services/etl_manager.git#egg=etl_manager
```

or git clone and `pip install .`

you now get the error:

```
ERROR: Some build dependencies for etl_manager from git+git://github.com/moj-analytical-services/etl_manager.git#egg=etl_manager conflict with the backend dependencies: jsonschema==3.1.1 is incompatible with jsonschema<3.1.0,>=3.0.0.
```

And further errors with incompatibilities with `awscli` as well.

I think we need to delete requirements.txt and relax some of the requirements in toml.

**Comment by isichei** [comment]
@RobinL did [this](https://github.com/moj-analytical-services/etl_manager/commit/8ee3e7419622b422cb7ce8cff5db7d50e157bff9#diff-522adf759addbd3b193c74ca85243f7d) fix?
