### ISSUE TITLE
Validation is incorrectly failing STRUCT and ARRAY columns

### ISSUE THREAD

**Issue by isichei** [moj-analytical-services/etl_manager#119]
```python
from etl_manager.meta import TableMeta

tab = TableMeta(name="test", location="blah", data_format = "json")
tab.add_column(name="col1", type="struct<k:character>", description="blah")
```
Raises an error:
```
ValueError: The data_type provided must match the supported data_type names: character, int, long, float, double, date, datetime, boolean, struct, array
```

Check is probably just looking for `struct` or `array` specifically rather than doing a correct test.

Also I think the [regex check](https://github.com/moj-analytical-services/etl_manager/blob/master/etl_manager/utils.py#L148) is failing for columns that _should_ be fine. Using [this](https://aws.amazon.com/blogs/big-data/create-tables-in-amazon-athena-from-nested-json-and-mappings-using-jsonserde/) as an example. Should add to a unit test.

**Comment by RobinL** [comment]
I just ran into this too!
