### ISSUE TITLE
Incorrect setter

### ISSUE THREAD

**Issue by calumabarnett** [moj-analytical-services/etl_manager#141]
I think the following line should set `self._glue_version`: https://github.com/moj-analytical-services/etl_manager/blob/49c524c7b724c104e716aad78e160be107cbce8c/etl_manager/etl.py#L218

**Comment by AnthonyCody** [comment]
Above is in branch `49c524c7b7`.

If it's wrong in that branch, is it also wrong in `master` branch?
https://github.com/moj-analytical-services/etl_manager/blob/7795c2f15667e51710f5eb1e7f12be2c3237fa94/etl_manager/etl.py#L262
