### ISSUE TITLE
create_glue_database doc string out of date

### ISSUE THREAD

**Issue by AnthonyCody** [moj-analytical-services/etl_manager#71]
Just upgraded to v2.0.0 from a very early version.
Running (SOP Engineering Draft) main.py  throws the following error when trying to call `create_glue_database` in meta.py:

> Traceback (most recent call last):
>   File "main.py", line 76, in <module>
>     db_st.create_glue_database()
>   File "/Users/anthonycody/.pyenv/versions/3.6.2/lib/python3.6/site-packages/etl_manager/meta.py", line 499, in create_glue_database
>     _glue_client.create_database(**db)
>   File "/Users/anthonycody/.pyenv/versions/3.6.2/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/Users/anthonycody/.pyenv/versions/3.6.2/lib/python3.6/site-packages/botocore/client.py", line 623, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.errorfactory.AlreadyExistsException: An error occurred (AlreadyExistsException) when calling the CreateDatabase operation: Database already exists.

It appears there's a code diff  in `create_glue_database` between old and new version, the following line has been deprecated:
`     del_resp = self.delete_glue_database()`

This appears (?) to be the cause of the error.

Comments for function (unchanged across versions) reads;
 _Creates a database in Glue based on the database object calling the method function. If a database with the same name (db.name) already exists it overwrites it._

Error indicates this is no longer the case

**Comment by isichei** [comment]
Ah yeah we got rid of this - as people were accidentally deleting databases.

Was noted in the change log:
https://github.com/moj-analytical-services/etl_manager/blob/master/CHANGELOG.md#change-4

But didn't update the doc string

**Comment by isichei** [comment]
Posting link here to fix with next minor update.
https://github.com/moj-analytical-services/etl_manager/blob/master/etl_manager/meta.py#L490
